# install.ps1 — agenticToolset installer (Windows 11 / PowerShell 5.1+)
# Usage:
#   irm https://github.com/OWNER/REPO/releases/latest/download/install.ps1 | iex
#   $env:GITHUB_TOKEN = "ghp_xxx"; irm ... | iex   # for private repos

$ErrorActionPreference = "Stop"

$Repo       = "chingchangtw/agentic_toolset"
$ReleaseUrl = "https://github.com/$Repo/releases/latest/download/release.zip"
$ClaudeDir  = "$env:USERPROFILE\.claude"
$ProjectDir = (Get-Location).Path
$ProjectClaudeDir = "$ProjectDir\.claude"
$HooksDir   = "$ClaudeDir\hooks"
$SkillsDir  = "$ProjectClaudeDir\skills"
$Settings   = "$ClaudeDir\settings.json"
$TmpDir     = [System.IO.Path]::Combine([System.IO.Path]::GetTempPath(), [System.IO.Path]::GetRandomFileName())
New-Item -ItemType Directory -Path $TmpDir -Force | Out-Null

# ── download ──────────────────────────────────────────────────────────────────

Write-Host "→ Downloading release..."
$Headers = @{}
if ($env:GITHUB_TOKEN) { $Headers["Authorization"] = "Bearer $env:GITHUB_TOKEN" }
Invoke-WebRequest -Uri $ReleaseUrl -OutFile "$TmpDir\release.zip" -Headers $Headers
Expand-Archive -Path "$TmpDir\release.zip" -DestinationPath $TmpDir -Force

# ── skills ────────────────────────────────────────────────────────────────────

Write-Host "→ Installing skills → $SkillsDir\"
New-Item -ItemType Directory -Path $SkillsDir -Force | Out-Null
$SkillsSrc = "$TmpDir\skills"
if (Test-Path $SkillsSrc) {
    foreach ($skillDir in Get-ChildItem -Path $SkillsSrc -Directory) {
        $dest = Join-Path $SkillsDir $skillDir.Name
        Copy-Item -Path $skillDir.FullName -Destination $dest -Recurse -Force
        Write-Host "   ✓ skill: $($skillDir.Name)"
    }
}

# ── hooks ─────────────────────────────────────────────────────────────────────

Write-Host "→ Installing hooks → $HooksDir\"
New-Item -ItemType Directory -Path $HooksDir -Force | Out-Null
$HookSrc = "$TmpDir\hook"
if (Test-Path $HookSrc) {
    Copy-Item "$HookSrc\ts-session-guard.ps1"     "$HooksDir\ts-session-guard.ps1"  -Force
    Copy-Item "$HookSrc\ts-statusline_bridge.ps1" "$HooksDir\ts-statusline_bridge.ps1" -Force
    Write-Host "   ✓ ts-session-guard.ps1"
    Write-Host "   ✓ ts-statusline_bridge.ps1"
}

# ── settings.json ─────────────────────────────────────────────────────────────

Write-Host "→ Patching $Settings"
New-Item -ItemType Directory -Path $ClaudeDir -Force | Out-Null

$HookCmd  = "pwsh -NoProfile -File `"$HooksDir\ts-session-guard.ps1`""
$BridgeCmd = "pwsh -NoProfile -File `"$HooksDir\ts-statusline_bridge.ps1`""

$settings = @{}
if (Test-Path $Settings) {
    try { $settings = Get-Content $Settings -Raw -Encoding UTF8 | ConvertFrom-Json -AsHashtable }
    catch { $settings = @{} }
}

# UserPromptSubmit hook (idempotent)
if (-not $settings.ContainsKey("hooks")) { $settings["hooks"] = @{} }
if (-not $settings["hooks"].ContainsKey("UserPromptSubmit")) {
    $settings["hooks"]["UserPromptSubmit"] = @()
}
$ups = $settings["hooks"]["UserPromptSubmit"]
$alreadyReg = $ups | ForEach-Object {
    if ($_.hooks) { $_.hooks | Where-Object { $_.command -eq $HookCmd } }
} | Select-Object -First 1
if (-not $alreadyReg) {
    $settings["hooks"]["UserPromptSubmit"] += @{
        hooks = @(@{ type = "command"; command = $HookCmd })
    }
}

# statusLine
$existingSl = $settings["statusLine"]
if (-not $existingSl) {
    $settings["statusLine"] = $BridgeCmd
} elseif ($existingSl -ne $BridgeCmd) {
    # Conflict: write a wrapper ps1 that calls both
    $wrapperPath = "$HooksDir\statusline_wrapper.ps1"
    $wrapperContent = @"
# Auto-generated by agenticToolset installer
`$raw = [Console]::In.ReadToEnd()
try { `$raw | pwsh -NoProfile -File "$HooksDir\ts-statusline_bridge.ps1" 2>`$null } catch {}
`$raw | $existingSl
"@
    Set-Content -Path $wrapperPath -Value $wrapperContent -Encoding UTF8
    $settings["statusLine"] = "pwsh -NoProfile -File `"$wrapperPath`""
    Write-Host "   ⚠  Existing statusLine detected — wrapper written to $wrapperPath"
}

$settings | ConvertTo-Json -Depth 10 | Set-Content -Path $Settings -Encoding UTF8
Write-Host "   ✓ settings.json patched"

# ── scaffold ──────────────────────────────────────────────────────────────────

$ScaffoldSrc = "$TmpDir\scaffold"
if (Test-Path $ScaffoldSrc) {
    $answer = Read-Host "→ Scaffold project root? Copy templates to current dir ($PWD) [y/N]"
    if ($answer -match '^[yY]') {
        foreach ($item in Get-ChildItem -Path $ScaffoldSrc) {
            $dest = Join-Path $PWD $item.Name
            if (Test-Path $dest) {
                $ow = Read-Host "   $($item.Name) already exists — overwrite? [y/N]"
                if ($ow -notmatch '^[yY]') { Write-Host "   skip $($item.Name)"; continue }
            }
            Copy-Item -Path $item.FullName -Destination $dest -Recurse -Force
            Write-Host "   ✓ $($item.Name)"
        }
    }
}

# ── cleanup ───────────────────────────────────────────────────────────────────

Remove-Item -Recurse -Force $TmpDir -ErrorAction SilentlyContinue

Write-Host ""
Write-Host "✓ Done. Reload Claude Code to activate hooks."
Write-Host ""
Write-Host "  Next: install third-party skills:"
Write-Host "    npx skills add caveman-commit@latest"
Write-Host "    npx skills add spectra@latest"
